// Tree related
export const CHILDREN_RECEIVED = 'CHILDREN_RECEIVED';
export const CHILDREN_REQUESTED = 'CHILDREN_REQUESTED';
export const COLLAPSE_FOLDER_WAS_CLICKED = 'COLLAPSE_FOLDER_WAS_CLICKED';
export const EXPAND_FOLDER_WAS_CLICKED = 'EXPAND_FOLDER_WAS_CLICKED';
export const TOGGLE_FILE_SELECTED_WAS_CLICKED = 'TOGGLE_FILE_SELECTED_WAS_CLICKED';
export const TOGGLE_FOLDER_SELECTED_WAS_CLICKED = 'TOGGLE_FOLDER_SELECTED_WAS_CLICKED';

// Query related
export const CLEAR_QUERY_WAS_CLICKED = 'CLEAR_QUERY_WAS_CLICKED';
export const INITIATE_BUILD_QUERY = 'INITIATE_BUILD_QUERY';
export const STORE_QUERY_WAS_CLICKED = 'STORE_QUERY_WAS_CLICKED';
export const OPEN_BUILD_QUERY_DIALOG = 'OPEN_BUILD_QUERY_DIALOG';
export const CLOSE_BUILD_QUERY_DIALOG = 'CLOSE_BUILD_QUERY_DIALOG';
export const OPEN_CLEAR_QUERY_DIALOG = 'OPEN_CLEAR_QUERY_DIALOG';
export const CLOSE_CLEAR_QUERY_DIALOG = 'CLOSE_CLEAR_QUERY_DIALOG';
export const QUERY_TEXT_CHANGED = 'QUERY_TEXT_CHANGED';

// Searchbox related
export const TEXT_SEARCH_INPUT_CHANGED = 'TEXT_SEARCH_INPUT_CHANGED';
export const TEXT_SEARCH_RESULT_RECEIVED = 'TEXT_SEARCH_RESULT_RECEIVED';
