export const CHILDREN_RECEIVED = 'CHILDREN_RECEIVED';
export const CHILDREN_REQUESTED = 'CHILDREN_REQUESTED';
export const COLLAPSE_FOLDER_WAS_CLICKED = 'COLLAPSE_FOLDER_WAS_CLICKED';
export const EXPAND_FOLDER_WAS_CLICKED = 'EXPAND_FOLDER_WAS_CLICKED';
export const TOGGLE_FILE_SELECTED_WAS_CLICKED = 'TOGGLE_FILE_SELECTED_WAS_CLICKED';
